// <auto-generated />
namespace ProjetoFinalFaculdade.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adicionadaValidacaoIdadeMinimaAluno : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicionadaValidacaoIdadeMinimaAluno));
        
        string IMigrationMetadata.Id
        {
            get { return "201710311521073_adicionadaValidacaoIdadeMinimaAluno"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
